### ISSUE TITLE
Importing Pidgin configuration is broken.

### ISSUE THREAD

**Issue by filternetz** [twstrike/coyim#292] opened 2016-03-24 15:15 UTC
As a user, when I get prompted to import user data and I see my accounts listed which I want to import and I click on adding these accounts, nothing happens.

I was expecting that these accounts would be imported as I clearly added them explicitly.

This happens on Coy 0.3.1.
I run: Ubuntu 14.04.4 LTS \n \l
ii  pidgin                                                      1:2.10.9-0ubuntu3.2                                 amd64        graphical multi-protocol instant messaging client for X

**Comment by olabini** [comment] 2016-03-24 15:34
I'm sorry to hear that. Can you run Coy with the -debug flag and report the output when you try to import?

**Comment by olabini** [comment] 2016-03-24 15:50
I tried to replicate it locally, but the import work as expected.

**Comment by filternetz** [comment] 2016-03-24 16:52
This is really the only output I get:

[CoyIM] 2016/03/24 17:51:35 /home/travis/gopath/src/github.com/twstrike/coyim/gui/ui_reader.go:37: gui: loading compiled definition "Importer"

**Comment by olabini** [comment] 2016-03-24 17:29
That's very surprising. You checked one of the accounts and then pressed the import button?

**Comment by olabini** [comment] 2016-04-03 16:35
Any more news on this?

**Comment by filternetz** [comment] 2016-04-04 12:48
I run into the same issue on: 0.3.2

[CoyIM] 2016/04/04 14:42:51 /home/travis/gopath/src/github.com/twstrike/coyim/gui/ui_reader.go:37: gui: loading compiled definition "Importer"

I see the accounts but I can't import :-/

```
echo $HOME
/home/users/johndoe

ls /home/users/johndoe/.purple/

accels  accounts.xml  blist.xml  certificates  custom_smiley  icons  logs  otr.fingerprints  otr.instance_tags  otr.private_key  prefs.xml  smileys  smileys.xml  status.xml  xmpp-caps.xml

```

Can I do anything to provide you with more information?

**Comment by olabini** [comment] 2016-04-04 13:24
Hi, sorry about this. Can you just confirm that this is what you're doing:
- Press Accounts menu, then Import... 
- Check at least one of the accounts
- Press the import button

What happens then? Nothing? Does the window close, or does it stay open?

**Comment by filternetz** [comment] 2016-04-04 13:30
Sure, what I do is, I go to Accounts --> Import, see two accounts, check one or both of them, click import button the window closes. But not accounts are added.

**Comment by filternetz** [comment] 2016-04-04 13:35
Same problem goes with a clean coyim environment when you have to set it up, sees accounts, check boxes, click import button, window closes but no accounts are added.

**Comment by olabini** [comment] 2016-04-04 13:37
That's extremely strange. I'm a bit at a loss on how to debug it. Do you have the capability to build Coy yourself? In that case I can push a branch with some more specific debug information about the import process.

**Comment by filternetz** [comment] 2016-04-04 13:39
Sure thing, if you have any pointers I could follow i'll report back! :)

Thanks for the work! :+1:

**Comment by olabini** [comment] 2016-04-04 13:42
ok, great. give me a few minutes. =)

**Comment by olabini** [comment] 2016-04-04 13:49
OK, I've just pushed an updated branch. Checkout the coyim github repository, switch to the branch import-debug and do "make build-gui"
You should then be able to run CoyIM:
bin/coyim -debug

It should show you some more useful information.

**Comment by ageis** [comment] 2016-04-04 18:37
I have the same issue here. Cannot import an `otr.private_key` file from Pidgin. I ran that branch in debug mode and there were no messages related to the import.

**Comment by ageis** [comment] 2016-04-04 18:51
Update: I manually deleted all other accounts in my `otr.private_key` file that weren't needed, and the key successfully imported. One bug is that the fingerprint in the configuration window is not updated right away post-import. You need to re-open the preferences for the new fingerprint to show. 

As part of debugging the issue, I also tried manually editing the keys file and deleting any accounts that were not protocol `prpl-jabber`. This included one account of type `prpl-aim`. I think this account was probably causing the error, because when I subsequently tried to import, I got the "choose a key from the list" prompt.

**Comment by olabini** [comment] 2016-04-04 23:09
@ageis - did you actually try to import it using Accounts -> Import, or did you use the feature to speficially import a private key? If the latter, it's different issue - would you mind opening a separate issue for that?

**Comment by ageis** [comment] 2016-04-05 01:28
@olabini I was using the interface at Accounts > Edit > Encryption.

**Comment by olabini** [comment] 2016-04-05 03:39
@Ageis - this ticket is about the Accounts > Import... screen - would you mind open a separate issue for your problem?

**Comment by olabini** [comment] 2016-09-09 08:06
Update on this?

**Comment by olabini** [comment] 2016-09-13 21:32
I'll close this issue for now - if we get more updates we will reopen it.

**Closed by olabini** 2016-09-13 21:32 UTC
Labels: bug

**Comment by ageis** [comment] 2016-09-13 21:57
@olabini Were you not able to reproduce? Your [Pidgin import code](https://github.com/twstrike/coyim/blob/master/config/importer/pidgin.go#L61) only looks for protocol prpl-jabber. Your `pidgin_test_data` does not contain any other protocols. I assure you if you try importing keys from a file that contains non-XMPP accounts like AIM, etc. you will find the bug. I had thought my earlier message was clear. Sorry I didn't open a separate issue.

**Comment by olabini** [comment] 2016-09-14 19:46
I've created issues #363 and #362 to track these issues. Sorry for missing it before.
