### ISSUE TITLE
Rosalie & Natalie pairing: Problems setting up dev env with Mac OS X

### ISSUE THREAD

**Issue by natalieesk** [twstrike/coyim#203] opened 2016-01-09 21:03 UTC
We came up with the following issues/ideas when setting up our dev environment on Macs:

- Makefile couldn't find golint. We added this to get it to run, but that may not be the cleanest way to fix the problem. We couldn't make a pull request because our tests were not passing.

```
lint:
	$(GOPATH)/bin/golint ./...
```

- We had 4 tests failing with the same issue: "expected 'could not authenticate to XMPP Server' but got 'unmarshal <iq> : EOF ". Is there something we didn't set up properly? If so, we may want to add that to the setup instructions. 

- It would be really helpful to have a technical overview of how coyim works (maybe a diagram? ;D) so that we understand the general data flow (or where data is stored). This would cut down the time for new people who are trying to understand the system. For example: Coyim talks with an xmpp server and integrates with tor in this way...

Thanks!

**Comment by tcz001** [comment] 2016-01-09 23:52
1. add $(GOPATH)/bin/ into your $PATH env will solve such kind of problem easily.
2. this is not expected, at least I never see this before, could you please attach all the failing logs here?

**Comment by jimmythompson** [comment] 2016-01-10 12:45
I think I'm getting the same failing tests as Natalie and Rosalie. Logs below:

```
----------------------------------------------------------------------
FAIL: connection_test.go:698: ConnectionXmppSuite.Test_Dial_continuesWithAuthenticationAfterRegistering

connection_test.go:727:
    c.Assert(err, Equals, ErrAuthenticationFailed)
... obtained *errors.errorString = &errors.errorString{s:"unmarshal <iq>: EOF"} ("unmarshal <iq>: EOF")
... expected *errors.errorString = &errors.errorString{s:"could not authenticate to the XMPP server"} ("could not authenticate to the XMPP server")

2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}

----------------------------------------------------------------------
FAIL: connection_test.go:736: ConnectionXmppSuite.Test_Dial_continuesWithAuthenticationAfterRegistering2

connection_test.go:765:
    c.Assert(err, Equals, ErrAuthenticationFailed)
... obtained *errors.errorString = &errors.errorString{s:"unmarshal <iq>: EOF"} ("unmarshal <iq>: EOF")
... expected *errors.errorString = &errors.errorString{s:"could not authenticate to the XMPP server"} ("could not authenticate to the XMPP server")

2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms [PLAIN]
2016/01/09 13:37:04 sasl: authenticating via PLAIN
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms [PLAIN]
2016/01/09 13:37:04 sasl: authenticating via PLAIN
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms []
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms [PLAIN]
2016/01/09 13:37:04 sasl: authenticating via PLAIN
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms [PLAIN]
2016/01/09 13:37:04 sasl: authenticating via PLAIN
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms [PLAIN]
2016/01/09 13:37:04 sasl: authenticating via PLAIN
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}

----------------------------------------------------------------------
FAIL: connection_test.go:813: ConnectionXmppSuite.Test_Dial_runsForm

connection_test.go:852:
    c.Assert(err, Equals, ErrAuthenticationFailed)
... obtained *errors.errorString = &errors.errorString{s:"unmarshal <iq>: EOF"} ("unmarshal <iq>: EOF")
... expected *errors.errorString = &errors.errorString{s:"could not authenticate to the XMPP server"} ("could not authenticate to the XMPP server")

2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}

----------------------------------------------------------------------
FAIL: connection_test.go:774: ConnectionXmppSuite.Test_Dial_sendsBackUsernameAndPassword

connection_test.go:803:
    c.Assert(err, Equals, ErrAuthenticationFailed)
... obtained *errors.errorString = &errors.errorString{s:"unmarshal <iq>: EOF"} ("unmarshal <iq>: EOF")
... expected *errors.errorString = &errors.errorString{s:"could not authenticate to the XMPP server"} ("could not authenticate to the XMPP server")

2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 sasl: server supports mechanisms [PLAIN]
2016/01/09 13:37:04 sasl: authenticating via PLAIN
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:04 xmpp: error receiving stanza. unexpected XMPP message clientx <message/>
2016/01/09 13:37:04 xmpp: error receiving stanza. EOF
2016/01/09 13:37:05 sasl: server supports mechanisms [FOO PLAIN]
2016/01/09 13:37:05 sasl: authenticating via PLAIN
2016/01/09 13:37:05 sasl: server supports mechanisms []
2016/01/09 13:37:05 sasl: server supports mechanisms [FOO PLAIN]
2016/01/09 13:37:05 sasl: authenticating via PLAIN
2016/01/09 13:37:05 sasl: server supports mechanisms [FOO PLAIN]
2016/01/09 13:37:05 sasl: authenticating via PLAIN
2016/01/09 13:37:05 sasl: server supports mechanisms [DIGEST-MD5]
2016/01/09 13:37:05 sasl: authenticating via DIGEST-MD5
2016/01/09 13:37:05 sasl: server supports mechanisms [DIGEST-MD5]
2016/01/09 13:37:05 sasl: authenticating via DIGEST-MD5
2016/01/09 13:37:05 sasl: server supports mechanisms [SCRAM-SHA-1]
2016/01/09 13:37:05 sasl: authenticating via SCRAM-SHA-1
2016/01/09 13:37:05 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:05 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:05 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:05 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:05 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:05 xmpp: received unhandled element: xml.ProcInst{Target:"xml", Inst:[]uint8{0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3d, 0x27, 0x31, 0x2e, 0x30, 0x27}}
2016/01/09 13:37:05 xmpp: sending closing stream tag
2016/01/09 13:37:05 xmpp: TCP closed
2016/01/09 13:37:05 xmpp: received closing stream tag
```

**Comment by olabini** [comment] 2016-01-11 13:41
This is a regression - I'm seeing it too.

**Comment by tcz001** [comment] 2016-01-11 17:06
I'm reverting the latest two commits, since the tests got some conflict with current implementation around the Registration process.

**Comment by olabini** [comment] 2016-01-21 15:37
I'll close this issue, since two of the tasks in it are solved. I will open a separate issue to track the need for architecture drawing.

**Closed by olabini** 2016-01-21 15:37 UTC
