### ISSUE TITLE
Add support for shared secret OTR verification

### ISSUE THREAD

**Issue by micahflee** [twstrike/coyim#240] opened 2016-02-11 18:51 UTC
It would be great if CoyIM could support the Socialist Millionaire Protocol to verify OTR conversations. I find that SMP is much more usable than manual fingerprint verification.

**Comment by juniorz** [comment] 2016-02-11 20:59
This is a duplicate of #23.

**Comment by olabini** [comment] 2016-02-12 18:44
I'm closing this as it is a duplicate.

**Closed by olabini** 2016-02-12 18:44 UTC
