### ISSUE TITLE
It is not possible to paste in the text fields of the pop ups

### ISSUE THREAD

**Issue by faustodelatog** [twstrike/coyim#207] opened 2016-01-13 03:08 UTC
On Mac OS X 10.11.2 is not possible paste the values with CMD + v, you need to right click on the the text field and then move with the arrow keys to select the "Paste" option.

Go to CoyIM application 
Click on Accounts or Contacts option
Click Add...
Try to paste some text

**Comment by olabini** [comment] 2016-01-13 14:39
Thanks, this is actually a duplicate of #189, so I'm closing this one now.

**Closed by olabini** 2016-01-13 14:39 UTC
