### ISSUE TITLE
password prompt when using gmail

### ISSUE THREAD

**Issue by ioerror** [twstrike/coyim#323] opened 2016-04-01 18:30 UTC
When attempting to use a PRISM enabled gmail account, I was unable to connect. Google sent emails saying that coy wasn't secure and at the same time, coy was in a loop asking me for the password over and over again. Happens every time with this account - it should fail and not prompt for the password repeatedly, I think.

**Comment by xSmurf** [comment] 2016-04-01 21:02
I think this is a duplicate of #168

**Comment by olabini** [comment] 2016-04-03 16:11
Agreed, it's a duplicate. The problem here is that currently CoyIM doesn't know whether you entered the wrong password or if there's another error. #168 is about recognizing the difference.

**Closed by olabini** 2016-04-03 16:11 UTC
